### PR TITLE
feature/whiteListUpdate

### PR DESCRIPTION
**Pull request by ttcloopy**
ignore this comment, or delete if you can :)

### CODE REVIEW

**Comment by mgracer48** [comment]
didnt the infinite devs tell you to not do this???

**Comment by judge2020** [comment]
Stop PR'ing this!

**Comment by mgracer48** [comment]
even i know this is not allowed XD

**Comment by starsky135** [comment]
Please keep comments related to the source.

**Comment by nkrypt** [comment]
NOOOOOOOOOO!

**Comment by misread** [comment]
@judge2020 ~~FUCK~~ *bleep*

**Pull request closed without merging**
