### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by Hypsu**
A timer letting us know how much increased gag experience/accuracy should to be added under how many total gags we have in our inv when we press the HOME button.

The hosting and invitations slots in the Event slot in the book should also be removed since there is no use in them atm. 

Also the TP glitch needs to be fixed. Toons are unable to tp to friends who are on a street in the same playground, it says they are moving when they are not.

### CODE REVIEW

**Comment by nkrypt** [comment]
facepalm

**Comment by Markgasus** [comment]
...

**Comment by kevman95** [comment]
I cant...Please learn how to github people...

**Comment by nkrypt** [comment]
626bfb8dbf11ce98532c01aa82f92a88 1

When you try to make an issue, but make a PR instead.

**Comment by Markgasus** [comment]
lool ^

**Comment by misread** [comment]
how many freaking times are we going to try to merge toontownfellowship/master into toontowninfinite.

It's not happening.

**Pull request closed without merging**
